# FORCED MEMORY SETTINGS - Do not move these lines
# This prevents "GC thrashing" and "Metaspace" errors during Dex merging
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -Dorg.gradle.daemon.performance.disable-logging=true
# Give the Kotlin/KSP daemon its own memory pool to handle Room processing
kotlin.daemon.jvmargs=-Xmx2048m

# Android & Gradle Performance
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true

# Windows File Lock Fix
# Disabling VFS watching prevents background processes from locking the 'build' folder on Windows
org.gradle.vfs.watch=false
